#!/bin/bash
source output.txt
printf "
$ad
$ad$ad
$ad$ad$ad
$ad$ad$soyad
$ad$ad$sehir
$ad$ad$memleket
$ad$ad$splaka
$ad$ad$mplaka
$ad$ad$yil
$ad$ad$dogumyil
$ad$ad$dogumay
$ad$ad$dogumgun
$ad$ad$takim
$ad$ad$ktakim
$ad$ad$tyil

$ad$soyad
$ad$soyad$ad
$ad$soyad$soyad
$ad$soyad$sehir
$ad$soyad$memleket
$ad$soyad$splaka
$ad$soyad$mplaka
$ad$soyad$yil
$ad$soyad$dogumyil
$ad$soyad$dogumay
$ad$soyad$dogumgun
$ad$soyad$takim
$ad$soyad$ktakim
$ad$soyad$tyil

$ad$sehir
$ad$sehir$ad
$ad$sehir$soyad
$ad$sehir$sehir
$ad$sehir$memleket
$ad$sehir$splaka
$ad$sehir$mplaka
$ad$sehir$yil
$ad$sehir$dogumyil
$ad$sehir$dogumay
$ad$sehir$dogumgun
$ad$sehir$takim
$ad$sehir$ktakim
$ad$sehir$tyil

$ad$memleket
$ad$memleket$ad
$ad$memleket$soyad
$ad$memleket$sehir
$ad$memleket$memleket
$ad$memleket$splaka
$ad$memleket$mplaka
$ad$memleket$yil
$ad$memleket$dogumyil
$ad$memleket$dogumay
$ad$memleket$dogumgun
$ad$memleket$takim
$ad$memleket$ktakim
$ad$memleket$tyil

$ad$splaka
$ad$splaka$ad
$ad$splaka$soyad
$ad$splaka$sehir
$ad$splaka$memleket
$ad$splaka$splaka
$ad$splaka$mplaka
$ad$splaka$yil
$ad$splaka$dogumyil
$ad$splaka$dogumay
$ad$splaka$dogumgun
$ad$splaka$takim
$ad$splaka$ktakim
$ad$splaka$tyil

$ad$mplaka
$ad$mplaka$ad
$ad$mplaka$soyad
$ad$mplaka$sehir
$ad$mplaka$memleket
$ad$mplaka$splaka
$ad$mplaka$mplaka
$ad$mplaka$yil
$ad$mplaka$dogumyil
$ad$mplaka$dogumay
$ad$mplaka$dogumgun
$ad$mplaka$takim
$ad$mplaka$ktakim
$ad$mplaka$tyil

$ad$yil
$ad$yil$ad
$ad$yil$soyad
$ad$yil$sehir
$ad$yil$memleket
$ad$yil$splaka
$ad$yil$mplaka
$ad$yil$yil
$ad$yil$dogumyil
$ad$yil$dogumay
$ad$yil$dogumgun
$ad$yil$takim
$ad$yil$ktakim
$ad$yil$tyil

$ad$dogumyil
$ad$dogumyil$ad
$ad$dogumyil$soyad
$ad$dogumyil$sehir
$ad$dogumyil$memleket
$ad$dogumyil$splaka
$ad$dogumyil$mplaka
$ad$dogumyil$yil
$ad$dogumyil$dogumyil
$ad$dogumyil$dogumay
$ad$dogumyil$dogumgun
$ad$dogumyil$takim
$ad$dogumyil$ktakim
$ad$dogumyil$tyil

$ad$dogumay
$ad$dogumay$ad
$ad$dogumay$soyad
$ad$dogumay$sehir
$ad$dogumay$memleket
$ad$dogumay$splaka
$ad$dogumay$mplaka
$ad$dogumay$yil
$ad$dogumay$dogumyil
$ad$dogumay$dogumay
$ad$dogumay$dogumgun
$ad$dogumay$takim
$ad$dogumay$ktakim
$ad$dogumay$tyil

$ad$dogumgun
$ad$dogumgun$ad
$ad$dogumgun$soyad
$ad$dogumgun$sehir
$ad$dogumgun$memleket
$ad$dogumgun$splaka
$ad$dogumgun$mplaka
$ad$dogumgun$yil
$ad$dogumgun$dogumyil
$ad$dogumgun$dogumay
$ad$dogumgun$dogumgun
$ad$dogumgun$takim
$ad$dogumgun$ktakim
$ad$dogumgun$tyil

$ad$takim
$ad$takim$ad
$ad$takim$soyad
$ad$takim$sehir
$ad$takim$memleket
$ad$takim$splaka
$ad$takim$mplaka
$ad$takim$yil
$ad$takim$dogumyil
$ad$takim$dogumay
$ad$takim$dogumgun
$ad$takim$takim
$ad$takim$ktakim
$ad$takim$tyil

$ad$ktakim
$ad$ktakim$ad
$ad$ktakim$soyad
$ad$ktakim$sehir
$ad$ktakim$memleket
$ad$ktakim$splaka
$ad$ktakim$mplaka
$ad$ktakim$yil
$ad$ktakim$dogumyil
$ad$ktakim$dogumay
$ad$ktakim$dogumgun
$ad$ktakim$takim
$ad$ktakim$ktakim
$ad$ktakim$tyil

$ad$tyil
$ad$tyil$ad
$ad$tyil$soyad
$ad$tyil$sehir
$ad$tyil$memleket
$ad$tyil$splaka
$ad$tyil$mplaka
$ad$tyil$yil
$ad$tyil$dogumyil
$ad$tyil$dogumay
$ad$tyil$dogumgun
$ad$tyil$takim
$ad$tyil$ktakim
$ad$tyil$tyil" >> ../wordlistt.txt
