#!/bin/bash
source output.txt
printf "
$dogumay
$dogumay$ad
$dogumay$ad$ad
$dogumay$ad$soyad
$dogumay$ad$sehir
$dogumay$ad$memleket
$dogumay$ad$splaka
$dogumay$ad$mplaka
$dogumay$ad$yil
$dogumay$ad$dogumyil
$dogumay$ad$dogumay
$dogumay$ad$dogumgun
$dogumay$ad$takim
$dogumay$ad$ktakim
$dogumay$ad$tyil

$dogumay$soyad
$dogumay$soyad$ad
$dogumay$soyad$soyad
$dogumay$soyad$sehir
$dogumay$soyad$memleket
$dogumay$soyad$splaka
$dogumay$soyad$mplaka
$dogumay$soyad$yil
$dogumay$soyad$dogumyil
$dogumay$soyad$dogumay
$dogumay$soyad$dogumgun
$dogumay$soyad$takim
$dogumay$soyad$ktakim
$dogumay$soyad$tyil

$dogumay$sehir
$dogumay$sehir$ad
$dogumay$sehir$soyad
$dogumay$sehir$sehir
$dogumay$sehir$memleket
$dogumay$sehir$splaka
$dogumay$sehir$mplaka
$dogumay$sehir$yil
$dogumay$sehir$dogumyil
$dogumay$sehir$dogumay
$dogumay$sehir$dogumgun
$dogumay$sehir$takim
$dogumay$sehir$ktakim
$dogumay$sehir$tyil

$dogumay$memleket
$dogumay$memleket$ad
$dogumay$memleket$soyad
$dogumay$memleket$sehir
$dogumay$memleket$memleket
$dogumay$memleket$splaka
$dogumay$memleket$mplaka
$dogumay$memleket$yil
$dogumay$memleket$dogumyil
$dogumay$memleket$dogumay
$dogumay$memleket$dogumgun
$dogumay$memleket$takim
$dogumay$memleket$ktakim
$dogumay$memleket$tyil

$dogumay$splaka
$dogumay$splaka$ad
$dogumay$splaka$soyad
$dogumay$splaka$sehir
$dogumay$splaka$memleket
$dogumay$splaka$splaka
$dogumay$splaka$mplaka
$dogumay$splaka$yil
$dogumay$splaka$dogumyil
$dogumay$splaka$dogumay
$dogumay$splaka$dogumgun
$dogumay$splaka$takim
$dogumay$splaka$ktakim
$dogumay$splaka$tyil

$dogumay$mplaka
$dogumay$mplaka$ad
$dogumay$mplaka$soyad
$dogumay$mplaka$sehir
$dogumay$mplaka$memleket
$dogumay$mplaka$splaka
$dogumay$mplaka$mplaka
$dogumay$mplaka$yil
$dogumay$mplaka$dogumyil
$dogumay$mplaka$dogumay
$dogumay$mplaka$dogumgun
$dogumay$mplaka$takim
$dogumay$mplaka$ktakim
$dogumay$mplaka$tyil

$dogumay$yil
$dogumay$yil$ad
$dogumay$yil$soyad
$dogumay$yil$sehir
$dogumay$yil$memleket
$dogumay$yil$splaka
$dogumay$yil$mplaka
$dogumay$yil$yil
$dogumay$yil$dogumyil
$dogumay$yil$dogumay
$dogumay$yil$dogumgun
$dogumay$yil$takim
$dogumay$yil$ktakim
$dogumay$yil$tyil

$dogumay$dogumyil
$dogumay$dogumyil$ad
$dogumay$dogumyil$soyad
$dogumay$dogumyil$sehir
$dogumay$dogumyil$memleket
$dogumay$dogumyil$splaka
$dogumay$dogumyil$mplaka
$dogumay$dogumyil$yil
$dogumay$dogumyil$dogumyil
$dogumay$dogumyil$dogumay
$dogumay$dogumyil$dogumgun
$dogumay$dogumyil$takim
$dogumay$dogumyil$ktakim
$dogumay$dogumyil$tyil

$dogumay$dogumay
$dogumay$dogumay$ad
$dogumay$dogumay$soyad
$dogumay$dogumay$sehir
$dogumay$dogumay$memleket
$dogumay$dogumay$splaka
$dogumay$dogumay$mplaka
$dogumay$dogumay$yil
$dogumay$dogumay$dogumyil
$dogumay$dogumay$dogumay
$dogumay$dogumay$dogumgun
$dogumay$dogumay$takim
$dogumay$dogumay$ktakim
$dogumay$dogumay$tyil

$dogumay$dogumgun
$dogumay$dogumgun$ad
$dogumay$dogumgun$soyad
$dogumay$dogumgun$sehir
$dogumay$dogumgun$memleket
$dogumay$dogumgun$splaka
$dogumay$dogumgun$mplaka
$dogumay$dogumgun$yil
$dogumay$dogumgun$dogumyil
$dogumay$dogumgun$dogumay
$dogumay$dogumgun$dogumgun
$dogumay$dogumgun$takim
$dogumay$dogumgun$ktakim
$dogumay$dogumgun$tyil

$dogumay$takim
$dogumay$takim$ad
$dogumay$takim$soyad
$dogumay$takim$sehir
$dogumay$takim$memleket
$dogumay$takim$splaka
$dogumay$takim$mplaka
$dogumay$takim$yil
$dogumay$takim$dogumyil
$dogumay$takim$dogumay
$dogumay$takim$dogumgun
$dogumay$takim$takim
$dogumay$takim$ktakim
$dogumay$takim$tyil

$dogumay$ktakim
$dogumay$ktakim$ad
$dogumay$ktakim$soyad
$dogumay$ktakim$sehir
$dogumay$ktakim$memleket
$dogumay$ktakim$splaka
$dogumay$ktakim$mplaka
$dogumay$ktakim$yil
$dogumay$ktakim$dogumyil
$dogumay$ktakim$dogumay
$dogumay$ktakim$dogumgun
$dogumay$ktakim$takim
$dogumay$ktakim$ktakim
$dogumay$ktakim$tyil

$dogumay$tyil
$dogumay$tyil$ad
$dogumay$tyil$soyad
$dogumay$tyil$sehir
$dogumay$tyil$memleket
$dogumay$tyil$splaka
$dogumay$tyil$mplaka
$dogumay$tyil$yil
$dogumay$tyil$dogumyil
$dogumay$tyil$dogumay
$dogumay$tyil$dogumgun
$dogumay$tyil$takim
$dogumay$tyil$ktakim
$dogumay$tyil$tyil" >> ../wordlistt.txt




