#!/bin/bash
source output.txt
printf "
$dogumgun
$dogumgun$ad
$dogumgun$ad$ad
$dogumgun$ad$soyad
$dogumgun$ad$sehir
$dogumgun$ad$memleket
$dogumgun$ad$splaka
$dogumgun$ad$mplaka
$dogumgun$ad$yil
$dogumgun$ad$dogumyil
$dogumgun$ad$dogumay
$dogumgun$ad$dogumgun
$dogumgun$ad$takim
$dogumgun$ad$ktakim
$dogumgun$ad$tyil

$dogumgun$soyad
$dogumgun$soyad$ad
$dogumgun$soyad$soyad
$dogumgun$soyad$sehir
$dogumgun$soyad$memleket
$dogumgun$soyad$splaka
$dogumgun$soyad$mplaka
$dogumgun$soyad$yil
$dogumgun$soyad$dogumyil
$dogumgun$soyad$dogumay
$dogumgun$soyad$dogumgun
$dogumgun$soyad$takim
$dogumgun$soyad$ktakim
$dogumgun$soyad$tyil

$dogumgun$sehir
$dogumgun$sehir$ad
$dogumgun$sehir$soyad
$dogumgun$sehir$sehir
$dogumgun$sehir$memleket
$dogumgun$sehir$splaka
$dogumgun$sehir$mplaka
$dogumgun$sehir$yil
$dogumgun$sehir$dogumyil
$dogumgun$sehir$dogumay
$dogumgun$sehir$dogumgun
$dogumgun$sehir$takim
$dogumgun$sehir$ktakim
$dogumgun$sehir$tyil

$dogumgun$memleket
$dogumgun$memleket$ad
$dogumgun$memleket$soyad
$dogumgun$memleket$sehir
$dogumgun$memleket$memleket
$dogumgun$memleket$splaka
$dogumgun$memleket$mplaka
$dogumgun$memleket$yil
$dogumgun$memleket$dogumyil
$dogumgun$memleket$dogumay
$dogumgun$memleket$dogumgun
$dogumgun$memleket$takim
$dogumgun$memleket$ktakim
$dogumgun$memleket$tyil

$dogumgun$splaka
$dogumgun$splaka$ad
$dogumgun$splaka$soyad
$dogumgun$splaka$sehir
$dogumgun$splaka$memleket
$dogumgun$splaka$splaka
$dogumgun$splaka$mplaka
$dogumgun$splaka$yil
$dogumgun$splaka$dogumyil
$dogumgun$splaka$dogumay
$dogumgun$splaka$dogumgun
$dogumgun$splaka$takim
$dogumgun$splaka$ktakim
$dogumgun$splaka$tyil

$dogumgun$mplaka
$dogumgun$mplaka$ad
$dogumgun$mplaka$soyad
$dogumgun$mplaka$sehir
$dogumgun$mplaka$memleket
$dogumgun$mplaka$splaka
$dogumgun$mplaka$mplaka
$dogumgun$mplaka$yil
$dogumgun$mplaka$dogumyil
$dogumgun$mplaka$dogumay
$dogumgun$mplaka$dogumgun
$dogumgun$mplaka$takim
$dogumgun$mplaka$ktakim
$dogumgun$mplaka$tyil

$dogumgun$yil
$dogumgun$yil$ad
$dogumgun$yil$soyad
$dogumgun$yil$sehir
$dogumgun$yil$memleket
$dogumgun$yil$splaka
$dogumgun$yil$mplaka
$dogumgun$yil$yil
$dogumgun$yil$dogumyil
$dogumgun$yil$dogumay
$dogumgun$yil$dogumgun
$dogumgun$yil$takim
$dogumgun$yil$ktakim
$dogumgun$yil$tyil

$dogumgun$dogumyil
$dogumgun$dogumyil$ad
$dogumgun$dogumyil$soyad
$dogumgun$dogumyil$sehir
$dogumgun$dogumyil$memleket
$dogumgun$dogumyil$splaka
$dogumgun$dogumyil$mplaka
$dogumgun$dogumyil$yil
$dogumgun$dogumyil$dogumyil
$dogumgun$dogumyil$dogumay
$dogumgun$dogumyil$dogumgun
$dogumgun$dogumyil$takim
$dogumgun$dogumyil$ktakim
$dogumgun$dogumyil$tyil

$dogumgun$dogumay
$dogumgun$dogumay$ad
$dogumgun$dogumay$soyad
$dogumgun$dogumay$sehir
$dogumgun$dogumay$memleket
$dogumgun$dogumay$splaka
$dogumgun$dogumay$mplaka
$dogumgun$dogumay$yil
$dogumgun$dogumay$dogumyil
$dogumgun$dogumay$dogumay
$dogumgun$dogumay$dogumgun
$dogumgun$dogumay$takim
$dogumgun$dogumay$ktakim
$dogumgun$dogumay$tyil

$dogumgun$dogumgun
$dogumgun$dogumgun$ad
$dogumgun$dogumgun$soyad
$dogumgun$dogumgun$sehir
$dogumgun$dogumgun$memleket
$dogumgun$dogumgun$splaka
$dogumgun$dogumgun$mplaka
$dogumgun$dogumgun$yil
$dogumgun$dogumgun$dogumyil
$dogumgun$dogumgun$dogumay
$dogumgun$dogumgun$dogumgun
$dogumgun$dogumgun$takim
$dogumgun$dogumgun$ktakim
$dogumgun$dogumgun$tyil

$dogumgun$takim
$dogumgun$takim$ad
$dogumgun$takim$soyad
$dogumgun$takim$sehir
$dogumgun$takim$memleket
$dogumgun$takim$splaka
$dogumgun$takim$mplaka
$dogumgun$takim$yil
$dogumgun$takim$dogumyil
$dogumgun$takim$dogumay
$dogumgun$takim$dogumgun
$dogumgun$takim$takim
$dogumgun$takim$ktakim
$dogumgun$takim$tyil

$dogumgun$ktakim
$dogumgun$ktakim$ad
$dogumgun$ktakim$soyad
$dogumgun$ktakim$sehir
$dogumgun$ktakim$memleket
$dogumgun$ktakim$splaka
$dogumgun$ktakim$mplaka
$dogumgun$ktakim$yil
$dogumgun$ktakim$dogumyil
$dogumgun$ktakim$dogumay
$dogumgun$ktakim$dogumgun
$dogumgun$ktakim$takim
$dogumgun$ktakim$ktakim
$dogumgun$ktakim$tyil

$dogumgun$tyil
$dogumgun$tyil$ad
$dogumgun$tyil$soyad
$dogumgun$tyil$sehir
$dogumgun$tyil$memleket
$dogumgun$tyil$splaka
$dogumgun$tyil$mplaka
$dogumgun$tyil$yil
$dogumgun$tyil$dogumyil
$dogumgun$tyil$dogumay
$dogumgun$tyil$dogumgun
$dogumgun$tyil$takim
$dogumgun$tyil$ktakim
$dogumgun$tyil$tyil" >> ../wordlistt.txt




