#!/bin/bash
source output.txt
printf "
$dogumyil
$dogumyil$ad
$dogumyil$ad$ad
$dogumyil$ad$soyad
$dogumyil$ad$sehir
$dogumyil$ad$memleket
$dogumyil$ad$splaka
$dogumyil$ad$mplaka
$dogumyil$ad$yil
$dogumyil$ad$dogumyil
$dogumyil$ad$dogumay
$dogumyil$ad$dogumgun
$dogumyil$ad$takim
$dogumyil$ad$ktakim
$dogumyil$ad$tyil

$dogumyil$soyad
$dogumyil$soyad$ad
$dogumyil$soyad$soyad
$dogumyil$soyad$sehir
$dogumyil$soyad$memleket
$dogumyil$soyad$splaka
$dogumyil$soyad$mplaka
$dogumyil$soyad$yil
$dogumyil$soyad$dogumyil
$dogumyil$soyad$dogumay
$dogumyil$soyad$dogumgun
$dogumyil$soyad$takim
$dogumyil$soyad$ktakim
$dogumyil$soyad$tyil

$dogumyil$sehir
$dogumyil$sehir$ad
$dogumyil$sehir$soyad
$dogumyil$sehir$sehir
$dogumyil$sehir$memleket
$dogumyil$sehir$splaka
$dogumyil$sehir$mplaka
$dogumyil$sehir$yil
$dogumyil$sehir$dogumyil
$dogumyil$sehir$dogumay
$dogumyil$sehir$dogumgun
$dogumyil$sehir$takim
$dogumyil$sehir$ktakim
$dogumyil$sehir$tyil

$dogumyil$memleket
$dogumyil$memleket$ad
$dogumyil$memleket$soyad
$dogumyil$memleket$sehir
$dogumyil$memleket$memleket
$dogumyil$memleket$splaka
$dogumyil$memleket$mplaka
$dogumyil$memleket$yil
$dogumyil$memleket$dogumyil
$dogumyil$memleket$dogumay
$dogumyil$memleket$dogumgun
$dogumyil$memleket$takim
$dogumyil$memleket$ktakim
$dogumyil$memleket$tyil

$dogumyil$splaka
$dogumyil$splaka$ad
$dogumyil$splaka$soyad
$dogumyil$splaka$sehir
$dogumyil$splaka$memleket
$dogumyil$splaka$splaka
$dogumyil$splaka$mplaka
$dogumyil$splaka$yil
$dogumyil$splaka$dogumyil
$dogumyil$splaka$dogumay
$dogumyil$splaka$dogumgun
$dogumyil$splaka$takim
$dogumyil$splaka$ktakim
$dogumyil$splaka$tyil

$dogumyil$mplaka
$dogumyil$mplaka$ad
$dogumyil$mplaka$soyad
$dogumyil$mplaka$sehir
$dogumyil$mplaka$memleket
$dogumyil$mplaka$splaka
$dogumyil$mplaka$mplaka
$dogumyil$mplaka$yil
$dogumyil$mplaka$dogumyil
$dogumyil$mplaka$dogumay
$dogumyil$mplaka$dogumgun
$dogumyil$mplaka$takim
$dogumyil$mplaka$ktakim
$dogumyil$mplaka$tyil

$dogumyil$yil
$dogumyil$yil$ad
$dogumyil$yil$soyad
$dogumyil$yil$sehir
$dogumyil$yil$memleket
$dogumyil$yil$splaka
$dogumyil$yil$mplaka
$dogumyil$yil$yil
$dogumyil$yil$dogumyil
$dogumyil$yil$dogumay
$dogumyil$yil$dogumgun
$dogumyil$yil$takim
$dogumyil$yil$ktakim
$dogumyil$yil$tyil

$dogumyil$dogumyil
$dogumyil$dogumyil$ad
$dogumyil$dogumyil$soyad
$dogumyil$dogumyil$sehir
$dogumyil$dogumyil$memleket
$dogumyil$dogumyil$splaka
$dogumyil$dogumyil$mplaka
$dogumyil$dogumyil$yil
$dogumyil$dogumyil$dogumyil
$dogumyil$dogumyil$dogumay
$dogumyil$dogumyil$dogumgun
$dogumyil$dogumyil$takim
$dogumyil$dogumyil$ktakim
$dogumyil$dogumyil$tyil

$dogumyil$dogumay
$dogumyil$dogumay$ad
$dogumyil$dogumay$soyad
$dogumyil$dogumay$sehir
$dogumyil$dogumay$memleket
$dogumyil$dogumay$splaka
$dogumyil$dogumay$mplaka
$dogumyil$dogumay$yil
$dogumyil$dogumay$dogumyil
$dogumyil$dogumay$dogumay
$dogumyil$dogumay$dogumgun
$dogumyil$dogumay$takim
$dogumyil$dogumay$ktakim
$dogumyil$dogumay$tyil

$dogumyil$dogumgun
$dogumyil$dogumgun$ad
$dogumyil$dogumgun$soyad
$dogumyil$dogumgun$sehir
$dogumyil$dogumgun$memleket
$dogumyil$dogumgun$splaka
$dogumyil$dogumgun$mplaka
$dogumyil$dogumgun$yil
$dogumyil$dogumgun$dogumyil
$dogumyil$dogumgun$dogumay
$dogumyil$dogumgun$dogumgun
$dogumyil$dogumgun$takim
$dogumyil$dogumgun$ktakim
$dogumyil$dogumgun$tyil

$dogumyil$takim
$dogumyil$takim$ad
$dogumyil$takim$soyad
$dogumyil$takim$sehir
$dogumyil$takim$memleket
$dogumyil$takim$splaka
$dogumyil$takim$mplaka
$dogumyil$takim$yil
$dogumyil$takim$dogumyil
$dogumyil$takim$dogumay
$dogumyil$takim$dogumgun
$dogumyil$takim$takim
$dogumyil$takim$ktakim
$dogumyil$takim$tyil

$dogumyil$ktakim
$dogumyil$ktakim$ad
$dogumyil$ktakim$soyad
$dogumyil$ktakim$sehir
$dogumyil$ktakim$memleket
$dogumyil$ktakim$splaka
$dogumyil$ktakim$mplaka
$dogumyil$ktakim$yil
$dogumyil$ktakim$dogumyil
$dogumyil$ktakim$dogumay
$dogumyil$ktakim$dogumgun
$dogumyil$ktakim$takim
$dogumyil$ktakim$ktakim
$dogumyil$ktakim$tyil

$dogumyil$tyil
$dogumyil$tyil$ad
$dogumyil$tyil$soyad
$dogumyil$tyil$sehir
$dogumyil$tyil$memleket
$dogumyil$tyil$splaka
$dogumyil$tyil$mplaka
$dogumyil$tyil$yil
$dogumyil$tyil$dogumyil
$dogumyil$tyil$dogumay
$dogumyil$tyil$dogumgun
$dogumyil$tyil$takim
$dogumyil$tyil$ktakim
$dogumyil$tyil$tyil" >> ../wordlistt.txt




