#!/bin/bash
source output.txt
printf "
$ktakim
$ktakim$ad
$ktakim$ad$ad
$ktakim$ad$soyad
$ktakim$ad$sehir
$ktakim$ad$memleket
$ktakim$ad$splaka
$ktakim$ad$mplaka
$ktakim$ad$yil
$ktakim$ad$dogumyil
$ktakim$ad$dogumay
$ktakim$ad$dogumgun
$ktakim$ad$takim
$ktakim$ad$ktakim
$ktakim$ad$tyil

$ktakim$soyad
$ktakim$soyad$ad
$ktakim$soyad$soyad
$ktakim$soyad$sehir
$ktakim$soyad$memleket
$ktakim$soyad$splaka
$ktakim$soyad$mplaka
$ktakim$soyad$yil
$ktakim$soyad$dogumyil
$ktakim$soyad$dogumay
$ktakim$soyad$dogumgun
$ktakim$soyad$takim
$ktakim$soyad$ktakim
$ktakim$soyad$tyil

$ktakim$sehir
$ktakim$sehir$ad
$ktakim$sehir$soyad
$ktakim$sehir$sehir
$ktakim$sehir$memleket
$ktakim$sehir$splaka
$ktakim$sehir$mplaka
$ktakim$sehir$yil
$ktakim$sehir$dogumyil
$ktakim$sehir$dogumay
$ktakim$sehir$dogumgun
$ktakim$sehir$takim
$ktakim$sehir$ktakim
$ktakim$sehir$tyil

$ktakim$memleket
$ktakim$memleket$ad
$ktakim$memleket$soyad
$ktakim$memleket$sehir
$ktakim$memleket$memleket
$ktakim$memleket$splaka
$ktakim$memleket$mplaka
$ktakim$memleket$yil
$ktakim$memleket$dogumyil
$ktakim$memleket$dogumay
$ktakim$memleket$dogumgun
$ktakim$memleket$takim
$ktakim$memleket$ktakim
$ktakim$memleket$tyil

$ktakim$splaka
$ktakim$splaka$ad
$ktakim$splaka$soyad
$ktakim$splaka$sehir
$ktakim$splaka$memleket
$ktakim$splaka$splaka
$ktakim$splaka$mplaka
$ktakim$splaka$yil
$ktakim$splaka$dogumyil
$ktakim$splaka$dogumay
$ktakim$splaka$dogumgun
$ktakim$splaka$takim
$ktakim$splaka$ktakim
$ktakim$splaka$tyil

$ktakim$mplaka
$ktakim$mplaka$ad
$ktakim$mplaka$soyad
$ktakim$mplaka$sehir
$ktakim$mplaka$memleket
$ktakim$mplaka$splaka
$ktakim$mplaka$mplaka
$ktakim$mplaka$yil
$ktakim$mplaka$dogumyil
$ktakim$mplaka$dogumay
$ktakim$mplaka$dogumgun
$ktakim$mplaka$takim
$ktakim$mplaka$ktakim
$ktakim$mplaka$tyil

$ktakim$yil
$ktakim$yil$ad
$ktakim$yil$soyad
$ktakim$yil$sehir
$ktakim$yil$memleket
$ktakim$yil$splaka
$ktakim$yil$mplaka
$ktakim$yil$yil
$ktakim$yil$dogumyil
$ktakim$yil$dogumay
$ktakim$yil$dogumgun
$ktakim$yil$takim
$ktakim$yil$ktakim
$ktakim$yil$tyil

$ktakim$dogumyil
$ktakim$dogumyil$ad
$ktakim$dogumyil$soyad
$ktakim$dogumyil$sehir
$ktakim$dogumyil$memleket
$ktakim$dogumyil$splaka
$ktakim$dogumyil$mplaka
$ktakim$dogumyil$yil
$ktakim$dogumyil$dogumyil
$ktakim$dogumyil$dogumay
$ktakim$dogumyil$dogumgun
$ktakim$dogumyil$takim
$ktakim$dogumyil$ktakim
$ktakim$dogumyil$tyil

$ktakim$dogumay
$ktakim$dogumay$ad
$ktakim$dogumay$soyad
$ktakim$dogumay$sehir
$ktakim$dogumay$memleket
$ktakim$dogumay$splaka
$ktakim$dogumay$mplaka
$ktakim$dogumay$yil
$ktakim$dogumay$dogumyil
$ktakim$dogumay$dogumay
$ktakim$dogumay$dogumgun
$ktakim$dogumay$takim
$ktakim$dogumay$ktakim
$ktakim$dogumay$tyil

$ktakim$dogumgun
$ktakim$dogumgun$ad
$ktakim$dogumgun$soyad
$ktakim$dogumgun$sehir
$ktakim$dogumgun$memleket
$ktakim$dogumgun$splaka
$ktakim$dogumgun$mplaka
$ktakim$dogumgun$yil
$ktakim$dogumgun$dogumyil
$ktakim$dogumgun$dogumay
$ktakim$dogumgun$dogumgun
$ktakim$dogumgun$takim
$ktakim$dogumgun$ktakim
$ktakim$dogumgun$tyil

$ktakim$takim
$ktakim$takim$ad
$ktakim$takim$soyad
$ktakim$takim$sehir
$ktakim$takim$memleket
$ktakim$takim$splaka
$ktakim$takim$mplaka
$ktakim$takim$yil
$ktakim$takim$dogumyil
$ktakim$takim$dogumay
$ktakim$takim$dogumgun
$ktakim$takim$takim
$ktakim$takim$ktakim
$ktakim$takim$tyil

$ktakim$ktakim
$ktakim$ktakim$ad
$ktakim$ktakim$soyad
$ktakim$ktakim$sehir
$ktakim$ktakim$memleket
$ktakim$ktakim$splaka
$ktakim$ktakim$mplaka
$ktakim$ktakim$yil
$ktakim$ktakim$dogumyil
$ktakim$ktakim$dogumay
$ktakim$ktakim$dogumgun
$ktakim$ktakim$takim
$ktakim$ktakim$ktakim
$ktakim$ktakim$tyil

$ktakim$tyil
$ktakim$tyil$ad
$ktakim$tyil$soyad
$ktakim$tyil$sehir
$ktakim$tyil$memleket
$ktakim$tyil$splaka
$ktakim$tyil$mplaka
$ktakim$tyil$yil
$ktakim$tyil$dogumyil
$ktakim$tyil$dogumay
$ktakim$tyil$dogumgun
$ktakim$tyil$takim
$ktakim$tyil$ktakim
$ktakim$tyil$tyil" >> ../wordlistt.txt




