#!/bin/bash
source output.txt
printf "
$memleket
$memleket$ad
$memleket$ad$ad
$memleket$ad$soyad
$memleket$ad$sehir
$memleket$ad$memleket
$memleket$ad$splaka
$memleket$ad$mplaka
$memleket$ad$yil
$memleket$ad$dogumyil
$memleket$ad$dogumay
$memleket$ad$dogumgun
$memleket$ad$takim
$memleket$ad$ktakim
$memleket$ad$tyil

$memleket$soyad
$memleket$soyad$ad
$memleket$soyad$soyad
$memleket$soyad$sehir
$memleket$soyad$memleket
$memleket$soyad$splaka
$memleket$soyad$mplaka
$memleket$soyad$yil
$memleket$soyad$dogumyil
$memleket$soyad$dogumay
$memleket$soyad$dogumgun
$memleket$soyad$takim
$memleket$soyad$ktakim
$memleket$soyad$tyil

$memleket$sehir
$memleket$sehir$ad
$memleket$sehir$soyad
$memleket$sehir$sehir
$memleket$sehir$memleket
$memleket$sehir$splaka
$memleket$sehir$mplaka
$memleket$sehir$yil
$memleket$sehir$dogumyil
$memleket$sehir$dogumay
$memleket$sehir$dogumgun
$memleket$sehir$takim
$memleket$sehir$ktakim
$memleket$sehir$tyil

$memleket$memleket
$memleket$memleket$ad
$memleket$memleket$soyad
$memleket$memleket$sehir
$memleket$memleket$memleket
$memleket$memleket$splaka
$memleket$memleket$mplaka
$memleket$memleket$yil
$memleket$memleket$dogumyil
$memleket$memleket$dogumay
$memleket$memleket$dogumgun
$memleket$memleket$takim
$memleket$memleket$ktakim
$memleket$memleket$tyil

$memleket$splaka
$memleket$splaka$ad
$memleket$splaka$soyad
$memleket$splaka$sehir
$memleket$splaka$memleket
$memleket$splaka$splaka
$memleket$splaka$mplaka
$memleket$splaka$yil
$memleket$splaka$dogumyil
$memleket$splaka$dogumay
$memleket$splaka$dogumgun
$memleket$splaka$takim
$memleket$splaka$ktakim
$memleket$splaka$tyil

$memleket$mplaka
$memleket$mplaka$ad
$memleket$mplaka$soyad
$memleket$mplaka$sehir
$memleket$mplaka$memleket
$memleket$mplaka$splaka
$memleket$mplaka$mplaka
$memleket$mplaka$yil
$memleket$mplaka$dogumyil
$memleket$mplaka$dogumay
$memleket$mplaka$dogumgun
$memleket$mplaka$takim
$memleket$mplaka$ktakim
$memleket$mplaka$tyil

$memleket$yil
$memleket$yil$ad
$memleket$yil$soyad
$memleket$yil$sehir
$memleket$yil$memleket
$memleket$yil$splaka
$memleket$yil$mplaka
$memleket$yil$yil
$memleket$yil$dogumyil
$memleket$yil$dogumay
$memleket$yil$dogumgun
$memleket$yil$takim
$memleket$yil$ktakim
$memleket$yil$tyil

$memleket$dogumyil
$memleket$dogumyil$ad
$memleket$dogumyil$soyad
$memleket$dogumyil$sehir
$memleket$dogumyil$memleket
$memleket$dogumyil$splaka
$memleket$dogumyil$mplaka
$memleket$dogumyil$yil
$memleket$dogumyil$dogumyil
$memleket$dogumyil$dogumay
$memleket$dogumyil$dogumgun
$memleket$dogumyil$takim
$memleket$dogumyil$ktakim
$memleket$dogumyil$tyil

$memleket$dogumay
$memleket$dogumay$ad
$memleket$dogumay$soyad
$memleket$dogumay$sehir
$memleket$dogumay$memleket
$memleket$dogumay$splaka
$memleket$dogumay$mplaka
$memleket$dogumay$yil
$memleket$dogumay$dogumyil
$memleket$dogumay$dogumay
$memleket$dogumay$dogumgun
$memleket$dogumay$takim
$memleket$dogumay$ktakim
$memleket$dogumay$tyil

$memleket$dogumgun
$memleket$dogumgun$ad
$memleket$dogumgun$soyad
$memleket$dogumgun$sehir
$memleket$dogumgun$memleket
$memleket$dogumgun$splaka
$memleket$dogumgun$mplaka
$memleket$dogumgun$yil
$memleket$dogumgun$dogumyil
$memleket$dogumgun$dogumay
$memleket$dogumgun$dogumgun
$memleket$dogumgun$takim
$memleket$dogumgun$ktakim
$memleket$dogumgun$tyil

$memleket$takim
$memleket$takim$ad
$memleket$takim$soyad
$memleket$takim$sehir
$memleket$takim$memleket
$memleket$takim$splaka
$memleket$takim$mplaka
$memleket$takim$yil
$memleket$takim$dogumyil
$memleket$takim$dogumay
$memleket$takim$dogumgun
$memleket$takim$takim
$memleket$takim$ktakim
$memleket$takim$tyil

$memleket$ktakim
$memleket$ktakim$ad
$memleket$ktakim$soyad
$memleket$ktakim$sehir
$memleket$ktakim$memleket
$memleket$ktakim$splaka
$memleket$ktakim$mplaka
$memleket$ktakim$yil
$memleket$ktakim$dogumyil
$memleket$ktakim$dogumay
$memleket$ktakim$dogumgun
$memleket$ktakim$takim
$memleket$ktakim$ktakim
$memleket$ktakim$tyil

$memleket$tyil
$memleket$tyil$ad
$memleket$tyil$soyad
$memleket$tyil$sehir
$memleket$tyil$memleket
$memleket$tyil$splaka
$memleket$tyil$mplaka
$memleket$tyil$yil
$memleket$tyil$dogumyil
$memleket$tyil$dogumay
$memleket$tyil$dogumgun
$memleket$tyil$takim
$memleket$tyil$ktakim
$memleket$tyil$tyil" >> ../wordlistt.txt



