#!/bin/bash
source output.txt
printf "
$mplaka
$mplaka$ad
$mplaka$ad$ad
$mplaka$ad$soyad
$mplaka$ad$sehir
$mplaka$ad$memleket
$mplaka$ad$splaka
$mplaka$ad$mplaka
$mplaka$ad$yil
$mplaka$ad$dogumyil
$mplaka$ad$dogumay
$mplaka$ad$dogumgun
$mplaka$ad$takim
$mplaka$ad$ktakim
$mplaka$ad$tyil

$mplaka$soyad
$mplaka$soyad$ad
$mplaka$soyad$soyad
$mplaka$soyad$sehir
$mplaka$soyad$memleket
$mplaka$soyad$splaka
$mplaka$soyad$mplaka
$mplaka$soyad$yil
$mplaka$soyad$dogumyil
$mplaka$soyad$dogumay
$mplaka$soyad$dogumgun
$mplaka$soyad$takim
$mplaka$soyad$ktakim
$mplaka$soyad$tyil

$mplaka$sehir
$mplaka$sehir$ad
$mplaka$sehir$soyad
$mplaka$sehir$sehir
$mplaka$sehir$memleket
$mplaka$sehir$splaka
$mplaka$sehir$mplaka
$mplaka$sehir$yil
$mplaka$sehir$dogumyil
$mplaka$sehir$dogumay
$mplaka$sehir$dogumgun
$mplaka$sehir$takim
$mplaka$sehir$ktakim
$mplaka$sehir$tyil

$mplaka$memleket
$mplaka$memleket$ad
$mplaka$memleket$soyad
$mplaka$memleket$sehir
$mplaka$memleket$memleket
$mplaka$memleket$splaka
$mplaka$memleket$mplaka
$mplaka$memleket$yil
$mplaka$memleket$dogumyil
$mplaka$memleket$dogumay
$mplaka$memleket$dogumgun
$mplaka$memleket$takim
$mplaka$memleket$ktakim
$mplaka$memleket$tyil

$mplaka$splaka
$mplaka$splaka$ad
$mplaka$splaka$soyad
$mplaka$splaka$sehir
$mplaka$splaka$memleket
$mplaka$splaka$splaka
$mplaka$splaka$mplaka
$mplaka$splaka$yil
$mplaka$splaka$dogumyil
$mplaka$splaka$dogumay
$mplaka$splaka$dogumgun
$mplaka$splaka$takim
$mplaka$splaka$ktakim
$mplaka$splaka$tyil

$mplaka$mplaka
$mplaka$mplaka$ad
$mplaka$mplaka$soyad
$mplaka$mplaka$sehir
$mplaka$mplaka$memleket
$mplaka$mplaka$splaka
$mplaka$mplaka$mplaka
$mplaka$mplaka$yil
$mplaka$mplaka$dogumyil
$mplaka$mplaka$dogumay
$mplaka$mplaka$dogumgun
$mplaka$mplaka$takim
$mplaka$mplaka$ktakim
$mplaka$mplaka$tyil

$mplaka$yil
$mplaka$yil$ad
$mplaka$yil$soyad
$mplaka$yil$sehir
$mplaka$yil$memleket
$mplaka$yil$splaka
$mplaka$yil$mplaka
$mplaka$yil$yil
$mplaka$yil$dogumyil
$mplaka$yil$dogumay
$mplaka$yil$dogumgun
$mplaka$yil$takim
$mplaka$yil$ktakim
$mplaka$yil$tyil

$mplaka$dogumyil
$mplaka$dogumyil$ad
$mplaka$dogumyil$soyad
$mplaka$dogumyil$sehir
$mplaka$dogumyil$memleket
$mplaka$dogumyil$splaka
$mplaka$dogumyil$mplaka
$mplaka$dogumyil$yil
$mplaka$dogumyil$dogumyil
$mplaka$dogumyil$dogumay
$mplaka$dogumyil$dogumgun
$mplaka$dogumyil$takim
$mplaka$dogumyil$ktakim
$mplaka$dogumyil$tyil

$mplaka$dogumay
$mplaka$dogumay$ad
$mplaka$dogumay$soyad
$mplaka$dogumay$sehir
$mplaka$dogumay$memleket
$mplaka$dogumay$splaka
$mplaka$dogumay$mplaka
$mplaka$dogumay$yil
$mplaka$dogumay$dogumyil
$mplaka$dogumay$dogumay
$mplaka$dogumay$dogumgun
$mplaka$dogumay$takim
$mplaka$dogumay$ktakim
$mplaka$dogumay$tyil

$mplaka$dogumgun
$mplaka$dogumgun$ad
$mplaka$dogumgun$soyad
$mplaka$dogumgun$sehir
$mplaka$dogumgun$memleket
$mplaka$dogumgun$splaka
$mplaka$dogumgun$mplaka
$mplaka$dogumgun$yil
$mplaka$dogumgun$dogumyil
$mplaka$dogumgun$dogumay
$mplaka$dogumgun$dogumgun
$mplaka$dogumgun$takim
$mplaka$dogumgun$ktakim
$mplaka$dogumgun$tyil

$mplaka$takim
$mplaka$takim$ad
$mplaka$takim$soyad
$mplaka$takim$sehir
$mplaka$takim$memleket
$mplaka$takim$splaka
$mplaka$takim$mplaka
$mplaka$takim$yil
$mplaka$takim$dogumyil
$mplaka$takim$dogumay
$mplaka$takim$dogumgun
$mplaka$takim$takim
$mplaka$takim$ktakim
$mplaka$takim$tyil

$mplaka$ktakim
$mplaka$ktakim$ad
$mplaka$ktakim$soyad
$mplaka$ktakim$sehir
$mplaka$ktakim$memleket
$mplaka$ktakim$splaka
$mplaka$ktakim$mplaka
$mplaka$ktakim$yil
$mplaka$ktakim$dogumyil
$mplaka$ktakim$dogumay
$mplaka$ktakim$dogumgun
$mplaka$ktakim$takim
$mplaka$ktakim$ktakim
$mplaka$ktakim$tyil

$mplaka$tyil
$mplaka$tyil$ad
$mplaka$tyil$soyad
$mplaka$tyil$sehir
$mplaka$tyil$memleket
$mplaka$tyil$splaka
$mplaka$tyil$mplaka
$mplaka$tyil$yil
$mplaka$tyil$dogumyil
$mplaka$tyil$dogumay
$mplaka$tyil$dogumgun
$mplaka$tyil$takim
$mplaka$tyil$ktakim
$mplaka$tyil$tyil" >> ../wordlistt.txt




