#!/bin/bash
source output.txt
printf "
$sehir
$sehir$ad
$sehir$ad$ad
$sehir$ad$soyad
$sehir$ad$sehir
$sehir$ad$memleket
$sehir$ad$splaka
$sehir$ad$mplaka
$sehir$ad$yil
$sehir$ad$dogumyil
$sehir$ad$dogumay
$sehir$ad$dogumgun
$sehir$ad$takim
$sehir$ad$ktakim
$sehir$ad$tyil

$sehir$soyad
$sehir$soyad$ad
$sehir$soyad$soyad
$sehir$soyad$sehir
$sehir$soyad$memleket
$sehir$soyad$splaka
$sehir$soyad$mplaka
$sehir$soyad$yil
$sehir$soyad$dogumyil
$sehir$soyad$dogumay
$sehir$soyad$dogumgun
$sehir$soyad$takim
$sehir$soyad$ktakim
$sehir$soyad$tyil

$sehir$sehir
$sehir$sehir$ad
$sehir$sehir$soyad
$sehir$sehir$sehir
$sehir$sehir$memleket
$sehir$sehir$splaka
$sehir$sehir$mplaka
$sehir$sehir$yil
$sehir$sehir$dogumyil
$sehir$sehir$dogumay
$sehir$sehir$dogumgun
$sehir$sehir$takim
$sehir$sehir$ktakim
$sehir$sehir$tyil

$sehir$memleket
$sehir$memleket$ad
$sehir$memleket$soyad
$sehir$memleket$sehir
$sehir$memleket$memleket
$sehir$memleket$splaka
$sehir$memleket$mplaka
$sehir$memleket$yil
$sehir$memleket$dogumyil
$sehir$memleket$dogumay
$sehir$memleket$dogumgun
$sehir$memleket$takim
$sehir$memleket$ktakim
$sehir$memleket$tyil

$sehir$splaka
$sehir$splaka$ad
$sehir$splaka$soyad
$sehir$splaka$sehir
$sehir$splaka$memleket
$sehir$splaka$splaka
$sehir$splaka$mplaka
$sehir$splaka$yil
$sehir$splaka$dogumyil
$sehir$splaka$dogumay
$sehir$splaka$dogumgun
$sehir$splaka$takim
$sehir$splaka$ktakim
$sehir$splaka$tyil

$sehir$mplaka
$sehir$mplaka$ad
$sehir$mplaka$soyad
$sehir$mplaka$sehir
$sehir$mplaka$memleket
$sehir$mplaka$splaka
$sehir$mplaka$mplaka
$sehir$mplaka$yil
$sehir$mplaka$dogumyil
$sehir$mplaka$dogumay
$sehir$mplaka$dogumgun
$sehir$mplaka$takim
$sehir$mplaka$ktakim
$sehir$mplaka$tyil

$sehir$yil
$sehir$yil$ad
$sehir$yil$soyad
$sehir$yil$sehir
$sehir$yil$memleket
$sehir$yil$splaka
$sehir$yil$mplaka
$sehir$yil$yil
$sehir$yil$dogumyil
$sehir$yil$dogumay
$sehir$yil$dogumgun
$sehir$yil$takim
$sehir$yil$ktakim
$sehir$yil$tyil

$sehir$dogumyil
$sehir$dogumyil$ad
$sehir$dogumyil$soyad
$sehir$dogumyil$sehir
$sehir$dogumyil$memleket
$sehir$dogumyil$splaka
$sehir$dogumyil$mplaka
$sehir$dogumyil$yil
$sehir$dogumyil$dogumyil
$sehir$dogumyil$dogumay
$sehir$dogumyil$dogumgun
$sehir$dogumyil$takim
$sehir$dogumyil$ktakim
$sehir$dogumyil$tyil

$sehir$dogumay
$sehir$dogumay$ad
$sehir$dogumay$soyad
$sehir$dogumay$sehir
$sehir$dogumay$memleket
$sehir$dogumay$splaka
$sehir$dogumay$mplaka
$sehir$dogumay$yil
$sehir$dogumay$dogumyil
$sehir$dogumay$dogumay
$sehir$dogumay$dogumgun
$sehir$dogumay$takim
$sehir$dogumay$ktakim
$sehir$dogumay$tyil

$sehir$dogumgun
$sehir$dogumgun$ad
$sehir$dogumgun$soyad
$sehir$dogumgun$sehir
$sehir$dogumgun$memleket
$sehir$dogumgun$splaka
$sehir$dogumgun$mplaka
$sehir$dogumgun$yil
$sehir$dogumgun$dogumyil
$sehir$dogumgun$dogumay
$sehir$dogumgun$dogumgun
$sehir$dogumgun$takim
$sehir$dogumgun$ktakim
$sehir$dogumgun$tyil

$sehir$takim
$sehir$takim$ad
$sehir$takim$soyad
$sehir$takim$sehir
$sehir$takim$memleket
$sehir$takim$splaka
$sehir$takim$mplaka
$sehir$takim$yil
$sehir$takim$dogumyil
$sehir$takim$dogumay
$sehir$takim$dogumgun
$sehir$takim$takim
$sehir$takim$ktakim
$sehir$takim$tyil

$sehir$ktakim
$sehir$ktakim$ad
$sehir$ktakim$soyad
$sehir$ktakim$sehir
$sehir$ktakim$memleket
$sehir$ktakim$splaka
$sehir$ktakim$mplaka
$sehir$ktakim$yil
$sehir$ktakim$dogumyil
$sehir$ktakim$dogumay
$sehir$ktakim$dogumgun
$sehir$ktakim$takim
$sehir$ktakim$ktakim
$sehir$ktakim$tyil

$sehir$tyil
$sehir$tyil$ad
$sehir$tyil$soyad
$sehir$tyil$sehir
$sehir$tyil$memleket
$sehir$tyil$splaka
$sehir$tyil$mplaka
$sehir$tyil$yil
$sehir$tyil$dogumyil
$sehir$tyil$dogumay
$sehir$tyil$dogumgun
$sehir$tyil$takim
$sehir$tyil$ktakim
$sehir$tyil$tyil" >> ../wordlistt.txt


