#!/bin/bash
source output.txt
printf "
$soyad
$soyad$ad
$soyad$ad$ad
$soyad$ad$soyad
$soyad$ad$sehir
$soyad$ad$memleket
$soyad$ad$splaka
$soyad$ad$mplaka
$soyad$ad$yil
$soyad$ad$dogumyil
$soyad$ad$dogumay
$soyad$ad$dogumgun
$soyad$ad$takim
$soyad$ad$ktakim
$soyad$ad$tyil

$soyad$soyad
$soyad$soyad$ad
$soyad$soyad$soyad
$soyad$soyad$sehir
$soyad$soyad$memleket
$soyad$soyad$splaka
$soyad$soyad$mplaka
$soyad$soyad$yil
$soyad$soyad$dogumyil
$soyad$soyad$dogumay
$soyad$soyad$dogumgun
$soyad$soyad$takim
$soyad$soyad$ktakim
$soyad$soyad$tyil

$soyad$sehir
$soyad$sehir$ad
$soyad$sehir$soyad
$soyad$sehir$sehir
$soyad$sehir$memleket
$soyad$sehir$splaka
$soyad$sehir$mplaka
$soyad$sehir$yil
$soyad$sehir$dogumyil
$soyad$sehir$dogumay
$soyad$sehir$dogumgun
$soyad$sehir$takim
$soyad$sehir$ktakim
$soyad$sehir$tyil

$soyad$memleket
$soyad$memleket$ad
$soyad$memleket$soyad
$soyad$memleket$sehir
$soyad$memleket$memleket
$soyad$memleket$splaka
$soyad$memleket$mplaka
$soyad$memleket$yil
$soyad$memleket$dogumyil
$soyad$memleket$dogumay
$soyad$memleket$dogumgun
$soyad$memleket$takim
$soyad$memleket$ktakim
$soyad$memleket$tyil

$soyad$splaka
$soyad$splaka$ad
$soyad$splaka$soyad
$soyad$splaka$sehir
$soyad$splaka$memleket
$soyad$splaka$splaka
$soyad$splaka$mplaka
$soyad$splaka$yil
$soyad$splaka$dogumyil
$soyad$splaka$dogumay
$soyad$splaka$dogumgun
$soyad$splaka$takim
$soyad$splaka$ktakim
$soyad$splaka$tyil

$soyad$mplaka
$soyad$mplaka$ad
$soyad$mplaka$soyad
$soyad$mplaka$sehir
$soyad$mplaka$memleket
$soyad$mplaka$splaka
$soyad$mplaka$mplaka
$soyad$mplaka$yil
$soyad$mplaka$dogumyil
$soyad$mplaka$dogumay
$soyad$mplaka$dogumgun
$soyad$mplaka$takim
$soyad$mplaka$ktakim
$soyad$mplaka$tyil

$soyad$yil
$soyad$yil$ad
$soyad$yil$soyad
$soyad$yil$sehir
$soyad$yil$memleket
$soyad$yil$splaka
$soyad$yil$mplaka
$soyad$yil$yil
$soyad$yil$dogumyil
$soyad$yil$dogumay
$soyad$yil$dogumgun
$soyad$yil$takim
$soyad$yil$ktakim
$soyad$yil$tyil

$soyad$dogumyil
$soyad$dogumyil$ad
$soyad$dogumyil$soyad
$soyad$dogumyil$sehir
$soyad$dogumyil$memleket
$soyad$dogumyil$splaka
$soyad$dogumyil$mplaka
$soyad$dogumyil$yil
$soyad$dogumyil$dogumyil
$soyad$dogumyil$dogumay
$soyad$dogumyil$dogumgun
$soyad$dogumyil$takim
$soyad$dogumyil$ktakim
$soyad$dogumyil$tyil

$soyad$dogumay
$soyad$dogumay$ad
$soyad$dogumay$soyad
$soyad$dogumay$sehir
$soyad$dogumay$memleket
$soyad$dogumay$splaka
$soyad$dogumay$mplaka
$soyad$dogumay$yil
$soyad$dogumay$dogumyil
$soyad$dogumay$dogumay
$soyad$dogumay$dogumgun
$soyad$dogumay$takim
$soyad$dogumay$ktakim
$soyad$dogumay$tyil

$soyad$dogumgun
$soyad$dogumgun$ad
$soyad$dogumgun$soyad
$soyad$dogumgun$sehir
$soyad$dogumgun$memleket
$soyad$dogumgun$splaka
$soyad$dogumgun$mplaka
$soyad$dogumgun$yil
$soyad$dogumgun$dogumyil
$soyad$dogumgun$dogumay
$soyad$dogumgun$dogumgun
$soyad$dogumgun$takim
$soyad$dogumgun$ktakim
$soyad$dogumgun$tyil

$soyad$takim
$soyad$takim$ad
$soyad$takim$soyad
$soyad$takim$sehir
$soyad$takim$memleket
$soyad$takim$splaka
$soyad$takim$mplaka
$soyad$takim$yil
$soyad$takim$dogumyil
$soyad$takim$dogumay
$soyad$takim$dogumgun
$soyad$takim$takim
$soyad$takim$ktakim
$soyad$takim$tyil

$soyad$ktakim
$soyad$ktakim$ad
$soyad$ktakim$soyad
$soyad$ktakim$sehir
$soyad$ktakim$memleket
$soyad$ktakim$splaka
$soyad$ktakim$mplaka
$soyad$ktakim$yil
$soyad$ktakim$dogumyil
$soyad$ktakim$dogumay
$soyad$ktakim$dogumgun
$soyad$ktakim$takim
$soyad$ktakim$ktakim
$soyad$ktakim$tyil

$soyad$tyil
$soyad$tyil$ad
$soyad$tyil$soyad
$soyad$tyil$sehir
$soyad$tyil$memleket
$soyad$tyil$splaka
$soyad$tyil$mplaka
$soyad$tyil$yil
$soyad$tyil$dogumyil
$soyad$tyil$dogumay
$soyad$tyil$dogumgun
$soyad$tyil$takim
$soyad$tyil$ktakim
$soyad$tyil$tyil" >> ../wordlistt.txt

