#!/bin/bash
source output.txt
printf "
$splaka
$splaka$ad
$splaka$ad$ad
$splaka$ad$soyad
$splaka$ad$sehir
$splaka$ad$memleket
$splaka$ad$splaka
$splaka$ad$mplaka
$splaka$ad$yil
$splaka$ad$dogumyil
$splaka$ad$dogumay
$splaka$ad$dogumgun
$splaka$ad$takim
$splaka$ad$ktakim
$splaka$ad$tyil

$splaka$soyad
$splaka$soyad$ad
$splaka$soyad$soyad
$splaka$soyad$sehir
$splaka$soyad$memleket
$splaka$soyad$splaka
$splaka$soyad$mplaka
$splaka$soyad$yil
$splaka$soyad$dogumyil
$splaka$soyad$dogumay
$splaka$soyad$dogumgun
$splaka$soyad$takim
$splaka$soyad$ktakim
$splaka$soyad$tyil

$splaka$sehir
$splaka$sehir$ad
$splaka$sehir$soyad
$splaka$sehir$sehir
$splaka$sehir$memleket
$splaka$sehir$splaka
$splaka$sehir$mplaka
$splaka$sehir$yil
$splaka$sehir$dogumyil
$splaka$sehir$dogumay
$splaka$sehir$dogumgun
$splaka$sehir$takim
$splaka$sehir$ktakim
$splaka$sehir$tyil

$splaka$memleket
$splaka$memleket$ad
$splaka$memleket$soyad
$splaka$memleket$sehir
$splaka$memleket$memleket
$splaka$memleket$splaka
$splaka$memleket$mplaka
$splaka$memleket$yil
$splaka$memleket$dogumyil
$splaka$memleket$dogumay
$splaka$memleket$dogumgun
$splaka$memleket$takim
$splaka$memleket$ktakim
$splaka$memleket$tyil

$splaka$splaka
$splaka$splaka$ad
$splaka$splaka$soyad
$splaka$splaka$sehir
$splaka$splaka$memleket
$splaka$splaka$splaka
$splaka$splaka$mplaka
$splaka$splaka$yil
$splaka$splaka$dogumyil
$splaka$splaka$dogumay
$splaka$splaka$dogumgun
$splaka$splaka$takim
$splaka$splaka$ktakim
$splaka$splaka$tyil

$splaka$mplaka
$splaka$mplaka$ad
$splaka$mplaka$soyad
$splaka$mplaka$sehir
$splaka$mplaka$memleket
$splaka$mplaka$splaka
$splaka$mplaka$mplaka
$splaka$mplaka$yil
$splaka$mplaka$dogumyil
$splaka$mplaka$dogumay
$splaka$mplaka$dogumgun
$splaka$mplaka$takim
$splaka$mplaka$ktakim
$splaka$mplaka$tyil

$splaka$yil
$splaka$yil$ad
$splaka$yil$soyad
$splaka$yil$sehir
$splaka$yil$memleket
$splaka$yil$splaka
$splaka$yil$mplaka
$splaka$yil$yil
$splaka$yil$dogumyil
$splaka$yil$dogumay
$splaka$yil$dogumgun
$splaka$yil$takim
$splaka$yil$ktakim
$splaka$yil$tyil

$splaka$dogumyil
$splaka$dogumyil$ad
$splaka$dogumyil$soyad
$splaka$dogumyil$sehir
$splaka$dogumyil$memleket
$splaka$dogumyil$splaka
$splaka$dogumyil$mplaka
$splaka$dogumyil$yil
$splaka$dogumyil$dogumyil
$splaka$dogumyil$dogumay
$splaka$dogumyil$dogumgun
$splaka$dogumyil$takim
$splaka$dogumyil$ktakim
$splaka$dogumyil$tyil

$splaka$dogumay
$splaka$dogumay$ad
$splaka$dogumay$soyad
$splaka$dogumay$sehir
$splaka$dogumay$memleket
$splaka$dogumay$splaka
$splaka$dogumay$mplaka
$splaka$dogumay$yil
$splaka$dogumay$dogumyil
$splaka$dogumay$dogumay
$splaka$dogumay$dogumgun
$splaka$dogumay$takim
$splaka$dogumay$ktakim
$splaka$dogumay$tyil

$splaka$dogumgun
$splaka$dogumgun$ad
$splaka$dogumgun$soyad
$splaka$dogumgun$sehir
$splaka$dogumgun$memleket
$splaka$dogumgun$splaka
$splaka$dogumgun$mplaka
$splaka$dogumgun$yil
$splaka$dogumgun$dogumyil
$splaka$dogumgun$dogumay
$splaka$dogumgun$dogumgun
$splaka$dogumgun$takim
$splaka$dogumgun$ktakim
$splaka$dogumgun$tyil

$splaka$takim
$splaka$takim$ad
$splaka$takim$soyad
$splaka$takim$sehir
$splaka$takim$memleket
$splaka$takim$splaka
$splaka$takim$mplaka
$splaka$takim$yil
$splaka$takim$dogumyil
$splaka$takim$dogumay
$splaka$takim$dogumgun
$splaka$takim$takim
$splaka$takim$ktakim
$splaka$takim$tyil

$splaka$ktakim
$splaka$ktakim$ad
$splaka$ktakim$soyad
$splaka$ktakim$sehir
$splaka$ktakim$memleket
$splaka$ktakim$splaka
$splaka$ktakim$mplaka
$splaka$ktakim$yil
$splaka$ktakim$dogumyil
$splaka$ktakim$dogumay
$splaka$ktakim$dogumgun
$splaka$ktakim$takim
$splaka$ktakim$ktakim
$splaka$ktakim$tyil

$splaka$tyil
$splaka$tyil$ad
$splaka$tyil$soyad
$splaka$tyil$sehir
$splaka$tyil$memleket
$splaka$tyil$splaka
$splaka$tyil$mplaka
$splaka$tyil$yil
$splaka$tyil$dogumyil
$splaka$tyil$dogumay
$splaka$tyil$dogumgun
$splaka$tyil$takim
$splaka$tyil$ktakim
$splaka$tyil$tyil" >> ../wordlistt.txt




