#!/bin/bash
source output.txt
printf "
$takim
$takim$ad
$takim$ad$ad
$takim$ad$soyad
$takim$ad$sehir
$takim$ad$memleket
$takim$ad$splaka
$takim$ad$mplaka
$takim$ad$yil
$takim$ad$dogumyil
$takim$ad$dogumay
$takim$ad$dogumgun
$takim$ad$takim
$takim$ad$ktakim
$takim$ad$tyil

$takim$soyad
$takim$soyad$ad
$takim$soyad$soyad
$takim$soyad$sehir
$takim$soyad$memleket
$takim$soyad$splaka
$takim$soyad$mplaka
$takim$soyad$yil
$takim$soyad$dogumyil
$takim$soyad$dogumay
$takim$soyad$dogumgun
$takim$soyad$takim
$takim$soyad$ktakim
$takim$soyad$tyil

$takim$sehir
$takim$sehir$ad
$takim$sehir$soyad
$takim$sehir$sehir
$takim$sehir$memleket
$takim$sehir$splaka
$takim$sehir$mplaka
$takim$sehir$yil
$takim$sehir$dogumyil
$takim$sehir$dogumay
$takim$sehir$dogumgun
$takim$sehir$takim
$takim$sehir$ktakim
$takim$sehir$tyil

$takim$memleket
$takim$memleket$ad
$takim$memleket$soyad
$takim$memleket$sehir
$takim$memleket$memleket
$takim$memleket$splaka
$takim$memleket$mplaka
$takim$memleket$yil
$takim$memleket$dogumyil
$takim$memleket$dogumay
$takim$memleket$dogumgun
$takim$memleket$takim
$takim$memleket$ktakim
$takim$memleket$tyil

$takim$splaka
$takim$splaka$ad
$takim$splaka$soyad
$takim$splaka$sehir
$takim$splaka$memleket
$takim$splaka$splaka
$takim$splaka$mplaka
$takim$splaka$yil
$takim$splaka$dogumyil
$takim$splaka$dogumay
$takim$splaka$dogumgun
$takim$splaka$takim
$takim$splaka$ktakim
$takim$splaka$tyil

$takim$mplaka
$takim$mplaka$ad
$takim$mplaka$soyad
$takim$mplaka$sehir
$takim$mplaka$memleket
$takim$mplaka$splaka
$takim$mplaka$mplaka
$takim$mplaka$yil
$takim$mplaka$dogumyil
$takim$mplaka$dogumay
$takim$mplaka$dogumgun
$takim$mplaka$takim
$takim$mplaka$ktakim
$takim$mplaka$tyil

$takim$yil
$takim$yil$ad
$takim$yil$soyad
$takim$yil$sehir
$takim$yil$memleket
$takim$yil$splaka
$takim$yil$mplaka
$takim$yil$yil
$takim$yil$dogumyil
$takim$yil$dogumay
$takim$yil$dogumgun
$takim$yil$takim
$takim$yil$ktakim
$takim$yil$tyil

$takim$dogumyil
$takim$dogumyil$ad
$takim$dogumyil$soyad
$takim$dogumyil$sehir
$takim$dogumyil$memleket
$takim$dogumyil$splaka
$takim$dogumyil$mplaka
$takim$dogumyil$yil
$takim$dogumyil$dogumyil
$takim$dogumyil$dogumay
$takim$dogumyil$dogumgun
$takim$dogumyil$takim
$takim$dogumyil$ktakim
$takim$dogumyil$tyil

$takim$dogumay
$takim$dogumay$ad
$takim$dogumay$soyad
$takim$dogumay$sehir
$takim$dogumay$memleket
$takim$dogumay$splaka
$takim$dogumay$mplaka
$takim$dogumay$yil
$takim$dogumay$dogumyil
$takim$dogumay$dogumay
$takim$dogumay$dogumgun
$takim$dogumay$takim
$takim$dogumay$ktakim
$takim$dogumay$tyil

$takim$dogumgun
$takim$dogumgun$ad
$takim$dogumgun$soyad
$takim$dogumgun$sehir
$takim$dogumgun$memleket
$takim$dogumgun$splaka
$takim$dogumgun$mplaka
$takim$dogumgun$yil
$takim$dogumgun$dogumyil
$takim$dogumgun$dogumay
$takim$dogumgun$dogumgun
$takim$dogumgun$takim
$takim$dogumgun$ktakim
$takim$dogumgun$tyil

$takim$takim
$takim$takim$ad
$takim$takim$soyad
$takim$takim$sehir
$takim$takim$memleket
$takim$takim$splaka
$takim$takim$mplaka
$takim$takim$yil
$takim$takim$dogumyil
$takim$takim$dogumay
$takim$takim$dogumgun
$takim$takim$takim
$takim$takim$ktakim
$takim$takim$tyil

$takim$ktakim
$takim$ktakim$ad
$takim$ktakim$soyad
$takim$ktakim$sehir
$takim$ktakim$memleket
$takim$ktakim$splaka
$takim$ktakim$mplaka
$takim$ktakim$yil
$takim$ktakim$dogumyil
$takim$ktakim$dogumay
$takim$ktakim$dogumgun
$takim$ktakim$takim
$takim$ktakim$ktakim
$takim$ktakim$tyil

$takim$tyil
$takim$tyil$ad
$takim$tyil$soyad
$takim$tyil$sehir
$takim$tyil$memleket
$takim$tyil$splaka
$takim$tyil$mplaka
$takim$tyil$yil
$takim$tyil$dogumyil
$takim$tyil$dogumay
$takim$tyil$dogumgun
$takim$tyil$takim
$takim$tyil$ktakim
$takim$tyil$tyil" >> ../wordlistt.txt




