#!/bin/bash
source output.txt
printf "
$tyil
$tyil$ad
$tyil$ad$ad
$tyil$ad$soyad
$tyil$ad$sehir
$tyil$ad$memleket
$tyil$ad$splaka
$tyil$ad$mplaka
$tyil$ad$yil
$tyil$ad$dogumyil
$tyil$ad$dogumay
$tyil$ad$dogumgun
$tyil$ad$takim
$tyil$ad$ktakim
$tyil$ad$tyil

$tyil$soyad
$tyil$soyad$ad
$tyil$soyad$soyad
$tyil$soyad$sehir
$tyil$soyad$memleket
$tyil$soyad$splaka
$tyil$soyad$mplaka
$tyil$soyad$yil
$tyil$soyad$dogumyil
$tyil$soyad$dogumay
$tyil$soyad$dogumgun
$tyil$soyad$takim
$tyil$soyad$ktakim
$tyil$soyad$tyil

$tyil$sehir
$tyil$sehir$ad
$tyil$sehir$soyad
$tyil$sehir$sehir
$tyil$sehir$memleket
$tyil$sehir$splaka
$tyil$sehir$mplaka
$tyil$sehir$yil
$tyil$sehir$dogumyil
$tyil$sehir$dogumay
$tyil$sehir$dogumgun
$tyil$sehir$takim
$tyil$sehir$ktakim
$tyil$sehir$tyil

$tyil$memleket
$tyil$memleket$ad
$tyil$memleket$soyad
$tyil$memleket$sehir
$tyil$memleket$memleket
$tyil$memleket$splaka
$tyil$memleket$mplaka
$tyil$memleket$yil
$tyil$memleket$dogumyil
$tyil$memleket$dogumay
$tyil$memleket$dogumgun
$tyil$memleket$takim
$tyil$memleket$ktakim
$tyil$memleket$tyil

$tyil$splaka
$tyil$splaka$ad
$tyil$splaka$soyad
$tyil$splaka$sehir
$tyil$splaka$memleket
$tyil$splaka$splaka
$tyil$splaka$mplaka
$tyil$splaka$yil
$tyil$splaka$dogumyil
$tyil$splaka$dogumay
$tyil$splaka$dogumgun
$tyil$splaka$takim
$tyil$splaka$ktakim
$tyil$splaka$tyil

$tyil$mplaka
$tyil$mplaka$ad
$tyil$mplaka$soyad
$tyil$mplaka$sehir
$tyil$mplaka$memleket
$tyil$mplaka$splaka
$tyil$mplaka$mplaka
$tyil$mplaka$yil
$tyil$mplaka$dogumyil
$tyil$mplaka$dogumay
$tyil$mplaka$dogumgun
$tyil$mplaka$takim
$tyil$mplaka$ktakim
$tyil$mplaka$tyil

$tyil$yil
$tyil$yil$ad
$tyil$yil$soyad
$tyil$yil$sehir
$tyil$yil$memleket
$tyil$yil$splaka
$tyil$yil$mplaka
$tyil$yil$yil
$tyil$yil$dogumyil
$tyil$yil$dogumay
$tyil$yil$dogumgun
$tyil$yil$takim
$tyil$yil$ktakim
$tyil$yil$tyil

$tyil$dogumyil
$tyil$dogumyil$ad
$tyil$dogumyil$soyad
$tyil$dogumyil$sehir
$tyil$dogumyil$memleket
$tyil$dogumyil$splaka
$tyil$dogumyil$mplaka
$tyil$dogumyil$yil
$tyil$dogumyil$dogumyil
$tyil$dogumyil$dogumay
$tyil$dogumyil$dogumgun
$tyil$dogumyil$takim
$tyil$dogumyil$ktakim
$tyil$dogumyil$tyil

$tyil$dogumay
$tyil$dogumay$ad
$tyil$dogumay$soyad
$tyil$dogumay$sehir
$tyil$dogumay$memleket
$tyil$dogumay$splaka
$tyil$dogumay$mplaka
$tyil$dogumay$yil
$tyil$dogumay$dogumyil
$tyil$dogumay$dogumay
$tyil$dogumay$dogumgun
$tyil$dogumay$takim
$tyil$dogumay$ktakim
$tyil$dogumay$tyil

$tyil$dogumgun
$tyil$dogumgun$ad
$tyil$dogumgun$soyad
$tyil$dogumgun$sehir
$tyil$dogumgun$memleket
$tyil$dogumgun$splaka
$tyil$dogumgun$mplaka
$tyil$dogumgun$yil
$tyil$dogumgun$dogumyil
$tyil$dogumgun$dogumay
$tyil$dogumgun$dogumgun
$tyil$dogumgun$takim
$tyil$dogumgun$ktakim
$tyil$dogumgun$tyil

$tyil$takim
$tyil$takim$ad
$tyil$takim$soyad
$tyil$takim$sehir
$tyil$takim$memleket
$tyil$takim$splaka
$tyil$takim$mplaka
$tyil$takim$yil
$tyil$takim$dogumyil
$tyil$takim$dogumay
$tyil$takim$dogumgun
$tyil$takim$takim
$tyil$takim$ktakim
$tyil$takim$tyil

$tyil$ktakim
$tyil$ktakim$ad
$tyil$ktakim$soyad
$tyil$ktakim$sehir
$tyil$ktakim$memleket
$tyil$ktakim$splaka
$tyil$ktakim$mplaka
$tyil$ktakim$yil
$tyil$ktakim$dogumyil
$tyil$ktakim$dogumay
$tyil$ktakim$dogumgun
$tyil$ktakim$takim
$tyil$ktakim$ktakim
$tyil$ktakim$tyil

$tyil$tyil
$tyil$tyil$ad
$tyil$tyil$soyad
$tyil$tyil$sehir
$tyil$tyil$memleket
$tyil$tyil$splaka
$tyil$tyil$mplaka
$tyil$tyil$yil
$tyil$tyil$dogumyil
$tyil$tyil$dogumay
$tyil$tyil$dogumgun
$tyil$tyil$takim
$tyil$tyil$ktakim
$tyil$tyil$tyil" >> ../wordlistt.txt




