#!/bin/bash
source output.txt
printf "
$yil
$yil$ad
$yil$ad$ad
$yil$ad$soyad
$yil$ad$sehir
$yil$ad$memleket
$yil$ad$splaka
$yil$ad$mplaka
$yil$ad$yil
$yil$ad$dogumyil
$yil$ad$dogumay
$yil$ad$dogumgun
$yil$ad$takim
$yil$ad$ktakim
$yil$ad$tyil

$yil$soyad
$yil$soyad$ad
$yil$soyad$soyad
$yil$soyad$sehir
$yil$soyad$memleket
$yil$soyad$splaka
$yil$soyad$mplaka
$yil$soyad$yil
$yil$soyad$dogumyil
$yil$soyad$dogumay
$yil$soyad$dogumgun
$yil$soyad$takim
$yil$soyad$ktakim
$yil$soyad$tyil

$yil$sehir
$yil$sehir$ad
$yil$sehir$soyad
$yil$sehir$sehir
$yil$sehir$memleket
$yil$sehir$splaka
$yil$sehir$mplaka
$yil$sehir$yil
$yil$sehir$dogumyil
$yil$sehir$dogumay
$yil$sehir$dogumgun
$yil$sehir$takim
$yil$sehir$ktakim
$yil$sehir$tyil

$yil$memleket
$yil$memleket$ad
$yil$memleket$soyad
$yil$memleket$sehir
$yil$memleket$memleket
$yil$memleket$splaka
$yil$memleket$mplaka
$yil$memleket$yil
$yil$memleket$dogumyil
$yil$memleket$dogumay
$yil$memleket$dogumgun
$yil$memleket$takim
$yil$memleket$ktakim
$yil$memleket$tyil

$yil$splaka
$yil$splaka$ad
$yil$splaka$soyad
$yil$splaka$sehir
$yil$splaka$memleket
$yil$splaka$splaka
$yil$splaka$mplaka
$yil$splaka$yil
$yil$splaka$dogumyil
$yil$splaka$dogumay
$yil$splaka$dogumgun
$yil$splaka$takim
$yil$splaka$ktakim
$yil$splaka$tyil

$yil$mplaka
$yil$mplaka$ad
$yil$mplaka$soyad
$yil$mplaka$sehir
$yil$mplaka$memleket
$yil$mplaka$splaka
$yil$mplaka$mplaka
$yil$mplaka$yil
$yil$mplaka$dogumyil
$yil$mplaka$dogumay
$yil$mplaka$dogumgun
$yil$mplaka$takim
$yil$mplaka$ktakim
$yil$mplaka$tyil

$yil$yil
$yil$yil$ad
$yil$yil$soyad
$yil$yil$sehir
$yil$yil$memleket
$yil$yil$splaka
$yil$yil$mplaka
$yil$yil$yil
$yil$yil$dogumyil
$yil$yil$dogumay
$yil$yil$dogumgun
$yil$yil$takim
$yil$yil$ktakim
$yil$yil$tyil

$yil$dogumyil
$yil$dogumyil$ad
$yil$dogumyil$soyad
$yil$dogumyil$sehir
$yil$dogumyil$memleket
$yil$dogumyil$splaka
$yil$dogumyil$mplaka
$yil$dogumyil$yil
$yil$dogumyil$dogumyil
$yil$dogumyil$dogumay
$yil$dogumyil$dogumgun
$yil$dogumyil$takim
$yil$dogumyil$ktakim
$yil$dogumyil$tyil

$yil$dogumay
$yil$dogumay$ad
$yil$dogumay$soyad
$yil$dogumay$sehir
$yil$dogumay$memleket
$yil$dogumay$splaka
$yil$dogumay$mplaka
$yil$dogumay$yil
$yil$dogumay$dogumyil
$yil$dogumay$dogumay
$yil$dogumay$dogumgun
$yil$dogumay$takim
$yil$dogumay$ktakim
$yil$dogumay$tyil

$yil$dogumgun
$yil$dogumgun$ad
$yil$dogumgun$soyad
$yil$dogumgun$sehir
$yil$dogumgun$memleket
$yil$dogumgun$splaka
$yil$dogumgun$mplaka
$yil$dogumgun$yil
$yil$dogumgun$dogumyil
$yil$dogumgun$dogumay
$yil$dogumgun$dogumgun
$yil$dogumgun$takim
$yil$dogumgun$ktakim
$yil$dogumgun$tyil

$yil$takim
$yil$takim$ad
$yil$takim$soyad
$yil$takim$sehir
$yil$takim$memleket
$yil$takim$splaka
$yil$takim$mplaka
$yil$takim$yil
$yil$takim$dogumyil
$yil$takim$dogumay
$yil$takim$dogumgun
$yil$takim$takim
$yil$takim$ktakim
$yil$takim$tyil

$yil$ktakim
$yil$ktakim$ad
$yil$ktakim$soyad
$yil$ktakim$sehir
$yil$ktakim$memleket
$yil$ktakim$splaka
$yil$ktakim$mplaka
$yil$ktakim$yil
$yil$ktakim$dogumyil
$yil$ktakim$dogumay
$yil$ktakim$dogumgun
$yil$ktakim$takim
$yil$ktakim$ktakim
$yil$ktakim$tyil

$yil$tyil
$yil$tyil$ad
$yil$tyil$soyad
$yil$tyil$sehir
$yil$tyil$memleket
$yil$tyil$splaka
$yil$tyil$mplaka
$yil$tyil$yil
$yil$tyil$dogumyil
$yil$tyil$dogumay
$yil$tyil$dogumgun
$yil$tyil$takim
$yil$tyil$ktakim
$yil$tyil$tyil" >> ../wordlistt.txt




